from typing import Annotated

from langgraph.graph import MessagesState
from typing_extensions import TypedDict


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    asset_type: Annotated[str, "Asset type under analysis such as stock or crypto"]
    instrument_context: Annotated[str, "Deterministic ticker identity resolved at run start"]
    trade_date: Annotated[str, "What date we are trading at"]

    # Pre-fetched data from Propagation node
    latest_close: Annotated[float | None, "Settled daily close (qfq) from sina minute bars"]
    latest_close_settled_at: Annotated[str | None, "Timestamp of settled close"]
    latest_close_realtime: Annotated[float | None, "Realtime intraday close (raw) from sina minute bars"]
    latest_close_realtime_at: Annotated[str | None, "Timestamp of realtime close"]
    news_block: Annotated[str | None, "Pre-fetched 7-day news block shared by News + Sentiment"]
    report_digest: Annotated[str, "Deterministic digest of all analyst reports"]
    fair_value_block: Annotated[str, "Pre-computed deterministic 5-model fair value (no LLM) — PM anchor"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Sentiment Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    macro_policy_report: Annotated[str, "Report from the Macro & Policy Analyst"]
    business_report: Annotated[str, "Report from the Business Analyst (segment breakdown)"]
    situation_report: Annotated[str, "Report from the Situation Analyst (price journey narrative)"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    # Deprecated — Trader node removed (v0.5).  Kept for back-compat with
    # memory-log entries, smoke tests, and _log_state serialisation.
    trader_investment_plan: Annotated[str, "Plan generated by the Trader (deprecated)"]

    # risk management team discussion step.
    # Aggressive and Conservative run in parallel after Research Manager.
    # They write to SEPARATE keys to avoid INVALID_CONCURRENT_GRAPH_UPDATE
    # (langgraph cannot apply a reducer to a nested TypedDict).  Neutral
    # reads both and synthesises them into ``risk_debate_state``.
    aggressive_risk_argument: Annotated[str, "Aggressive Analyst's debate argument (parallel)"]
    conservative_risk_argument: Annotated[str, "Conservative Analyst's debate argument (parallel)"]
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]
